- name: Windows | Check for xRemoteDesktopAdmin Powershell module
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present

- name: Windows | Enable Remote Desktop
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: Secure

- name: Windows | Check for xNetworking Powershell module
  win_psmodule:
    name: xNetworking
    state: present

- name: Firewall | Allow RDP through Firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Administrator access for RDP (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "3389"
    Protocol: "TCP"
    Description: "Opens the listener port for RDP"

- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - python
  - git
  - 7zip
  - sysinternals
  - pstools

- name: Change the hostname to DC01
  win_hostname:
    name: DC01
  register: win_hostname

- name: Reboot
  win_reboot:
  when: win_hostname.reboot_required
  
- name: Ensure that Administrator is present with a valid password
  win_user:
    name: Administrator
    password: StrongPass123!
    password_never_expires: yes
    state: present
  ignore_errors: yes

- name: Ensure that LAB.local domain exists
  win_domain:
    dns_domain_name: lab.local
    safe_mode_password: StrongPass123!
  register: check_domain

- name: Reboot to complete LAB.local domain creation
  win_reboot:
  when: check_domain.changed

- name: Ensure the server is a domain controller
  win_domain_controller:
    dns_domain_name: LAB.local
    domain_admin_user: Administrator@lab.local
    domain_admin_password: StrongPass123!
    safe_mode_password: StrongPass123!
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt
  register: check_domain_controller

- name: Reboot to complete domain controller setup
  win_reboot:
  when: check_domain_controller.changed

- name: Ensure that admin@LAB.local is present as Domain Admin
  win_domain_user:
    name: admin
    password: StrongPass123!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=lab,dc=local
    groups:
      - Domain Admins

- name: Ensure that bob@LAB.local is present in OU cn=Users,dc=LAB,dc=local
  win_domain_user:
    name: bob
    password: StrongPass123!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=lab,dc=local
    groups:
      - Users

- name: Ensure that alice@LAB.local is present in OU cn=Users,dc=LAB,dc=local
  win_domain_user:
    name: alice
    password: StrongPass123!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=lab,dc=local
    groups:
      - Users

- name: Create AllTeams group
  win_domain_group:
    name: allTeams
    scope: global
    path: DC=lab,DC=local
    state: present

- name: Create DBAOracle group
  win_domain_group:
    name: DBAOracle
    scope: global
    path: DC=lab,DC=local
    state: present

- name: Create DBASQLServer group
  win_domain_group:
    name: DBASQLServer
    scope: global
    path: DC=lab,DC=local
    state: present

- name: Create DBAMongo group
  win_domain_group:
    name: DBAMongo
    scope: global
    path: DC=lab,DC=local
    state: present

- name: Create DBARedis group
  win_domain_group:
    name: DBARedis
    scope: global
    path: DC=lab,DC=local
    state: present

- name: Create DBAEnterprise group
  win_domain_group:
    name: DBAEnterprise
    scope: global
    path: DC=lab,DC=local
    state: present

- name: Create a Test group
  win_domain_group:
    name: JustATestDemo
    scope: global
    path: DC=lab,DC=local
    state: present
