- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - git
  - 7zip
  - pstools
  - sysinternals

- name: Change the hostname to WKST01
  win_hostname:
    name: WKST01
  register: win_hostname

- name: Reboot
  # In case it stucks here saying "A system shutdown was in progress", reboot manually the vm and launch the playbook again
  win_reboot:
    reboot_timeout: 2000
  when: win_hostname.reboot_required

- name: Set configure dns
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 192.168.56.10
    log_path: C:\dns_log.txt

- name: Add to lab.local
  win_domain_membership:
    dns_domain_name: lab.local
    domain_admin_user: Administrator@lab.local
    domain_admin_password: StrongPass123!
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:
  when: domain_state.reboot_required

- name: Ensure that bob@lab.local is present as local administrator
  win_group_membership:
    name: Administrators
    Members:
     - bob@lab.local
    state: present