# tasks file for ansible-role-win2012r2-wmf51
# from https://github.com/andif888/ansible-role-win2012r2-wmf51/blob/d9bc8fb4cead22a09dbe8eec9d9db249fd07dc45/tasks/main.yml
- name: Download WMF5.1 installer
  win_get_url:
    url: https://go.microsoft.com/fwlink/?linkid=839516
    dest: C:\temp\Win8.1AndW2K12R2-KB3191564-x64.msu
  when: 
    - ansible_distribution.find("Server 2012 R2") != -1
    - ansible_powershell_version is version('5', '<') 

- name: Install WMF5.1
  win_hotfix:
    source: C:\temp\Win8.1AndW2K12R2-KB3191564-x64.msu
    state: present
  register: hotfix_install
  when: 
    - ansible_distribution.find("Server 2012 R2") != -1
    - ansible_powershell_version is version('5', '<') 

- name: reboot after WMF5.1 install
  win_reboot:
  when:
    - hotfix_install.changed
    - hotfix_install.reboot_required

- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - git
  - 7zip
  - pstools
  - sysinternals

- name: Change the hostname to DC02
  win_hostname:
    name: DC02
  register: win_hostname

- name: Reboot if needed
  win_reboot:
  when: win_hostname.reboot_required

- name: Set configure dns
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 192.168.56.10
    - 127.0.0.1
    log_path: C:\dns_log.txt

- name: Add to lab.local
  win_domain_membership:
    dns_domain_name: lab.local
    domain_admin_user: Administrator@lab.local
    domain_admin_password: StrongPass123!
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:
  when: domain_state.reboot_required
